### ISSUE TITLE
CSS/Form Field Render Issue

### ISSUE THREAD

**Issue by JJediny** [StackStorm/showcase-ansible-chatops#12]
Dropdowns on Form fields has the default css attribute `.st2-auto-form__field option` value was `color: white` wasn't sure if this was an already tweaked fix upstream. 

![image](https://cloud.githubusercontent.com/assets/6350035/20050127/6d070bae-a495-11e6-8f7c-910fc3804595.png)

![image](https://cloud.githubusercontent.com/assets/6350035/20050140/7bab9ae4-a495-11e6-8195-e5e30d525c28.png)

*From daily release of Chrome .deb on Ubuntu 14.04

**Comment by armab** [comment]
@JJediny Thanks for your report.

Moved to `st2web`: https://github.com/StackStorm/st2web/issues/333
