### ISSUE TITLE
Update to new packages

### ISSUE THREAD

**Issue by armab** [StackStorm/showcase-ansible-chatops#5]
Since old installing method is deprecated, update demo to use new bundled `st2` package from https://docs.stackstorm.com/install/deb.html

**Comment by LindsayHill** [comment]
I've started making some changes for this, similar to these changes https://github.com/StackStorm/st2-ansible-vagrant/commit/f8d62e7e92f43822408c1c78efe7027085e90fd3

Should get it tidied up soon. Will probably include changes required for #6

**Comment by armab** [comment]
Thanks for saying @LindsayHill , since I'm currently playing with this repo locally too.

But my thinking was to avoid using new install script https://stackstorm.com/packages/install.sh, because it's not idempotent and I'm not fan of installing additional `st2mistral` + `postgresql` dependencies when it's not needed (for this demo).

However I'm OK with your approach, go for it :+1: It would be probably simpler for user.

----
I'll play with ChatOps aliases then #6, because it was something I totally missed to try when we worked on new packages.

WDYT?

**Comment by LindsayHill** [comment]
@armab Take a look at this branch https://github.com/StackStorm/showcase-ansible-chatops/tree/migrate_to_packages

This uses the new packages method. I've done basic testing, and it looks OK so far. I haven't looked at the aliases at all. Can you give it a quick test?

**Comment by armab** [comment]
@LindsayHill Nice! Just open PR.

So far old aliases would work OK. I'll work on aliases improvements and include changes in next PR.
